name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      name: Test with the dotnet CLI
  run: dotnet test
    - name: Publish
      run: dotnet publish -c Release -o ./DemoCICD

  deploy-server-01:
    needs: build
    name: Deploy 01
    runs-on: self-hosted
    
    steps:
      - name: Deploy to IIS
        run: |
          Copy-Item ./DemoCICD/bin/Release/net6.0 C:/inetpub/wwwroot/DemoCICD -Recurse -Force
      - name: Run
        run: dotnet run ./DemoCICD/bin/Release/net6.0/DemoCICD.dll
